### ISSUE TITLE
Tracking issue: Code refactorings

### ISSUE THREAD

**Issue by Hirevo** [Hirevo/epitech-c-cpp-headers#11]
This is a tracking issue for the refactors that will happen for the extension.  

I think the code style is pretty poor at the moment.  
Some things to fix includes:
- [ ] Some things are inconsistent (like double quotes vs single quotes)
- [ ] Some code could be written to be more terse, more readable and more maintanable than it currently is.  
- [ ] The filenames are confusing, I don't even know why I did it this way.
